// This is used to get the AddOnProps for the various elements tested by ANDI
AndiData.getAddOnProps = function (element, elementData, extraProps) {
	//addOnProps[0] will be output generated by the add on properties. The rest are the properties.
	var addOnProps = [""];
	var prop;

	//===Get properties filtered by attribute name
	if (hasProp("aria-owns")) {
		displayAsId(prop);
		pushProp();
	}
	if (hasProp("aria-activedescendant")) {
		if (hasRole("application,group,textbox,combobox,grid,listbox,menu,menubar,radiogroup,row,rowgroup,select,tablist,toolbar,tree,treegrid")) {
			if (prop.val) {
				var activedescendant = document.getElementById(prop.val);
				if (activedescendant && $(activedescendant).is(":shown")) {//active descendant is visible
					//TODO: check if it's a true descendant
					var text = andiUtility.getVisibleInnerText(activedescendant, element);
					if (text)
						prop.out = text += " selected";
				}
				displayAsId(prop);
			}
		}
		pushProp();
	}
	if (hasProp("aria-checked")) {
		if (hasRole("option,radio,switch,menuitemcheckbox,menuitemradio,treeitem")) {
			if (prop.val === "true") {
				prop.out = "checked";
			} else {
				prop.out = "not checked";
			}
		} else if (hasRole("checkbox")) {
			if (prop.val === "true") {
				prop.out = "checked"
			} else {
				if (prop.val === "mixed") {
					prop.out =  "partially checked";
				} else {
					prop.out = "unchecked";
				}
			}
		}
			
		pushProp();
	}
	if (hasProp("aria-controls")) {
		displayAsId(prop);
		prop.out = "controls element";
		pushProp();
	}
	if (hasProp("aria-current")) {
		prop.out = "current " + prop.val;
		pushProp();
	}
	if (hasProp("aria-details")) {
		displayAsId(prop);
		prop.out = "has details";
		pushProp();
	}
	if (hasProp("aria-disabled") && prop.val === "true") {
		prop.out = "unavailable";
		pushProp();
	}
	if (hasProp("aria-errormessage")) {
		displayAsId(prop);
		pushProp();
	}
	if (hasProp("aria-haspopup")) {
		if (prop.val === "true" || prop.val === "menu") {
			prop.out = "menu";
		} else {
			if (prop.val === "listbox") {
				prop.out = "listbox";
			} else {
				if (prop.val === "tree") {
					prop.out = "tree";
				} else {
					if (prop.val === "grid") {
						prop.out = "grid";
					} else {
						if (prop.val === "dialog") {
							prop.out = "dialog"
						} else {
							prop.out = "";
						}
					}
				}
			}
		}
		pushProp();
	}
	if (elementData.isAriaHidden) {
		prop.name = "aria-hidden";
		prop.val = "true";
		prop.out = "";
		pushProp();
	}
	if (hasProp("aria-invalid") && prop.val === "true") {
		prop.out = "invalid entry";
		pushProp();
	}
	if (hasProp("aria-keyshortcuts")) {
		pushProp();
	}
	if (hasProp("aria-multiline")) {
		if (prop.val === "true" && hasRole("textbox,searchbox"))
			prop.out = "multi-line";
		pushProp();
	}
	if (hasProp("aria-multiselectable")) {
		if (prop.val === "true" && hasRole("grid,listbox,tablist,tree,treegrid"))
			prop.out = "multi-selectable";
		pushProp();
	}
	if (hasProp("aria-placeholder")) {
		pushProp();
	}
	if (hasProp("aria-pressed")) {
		if (hasRole("button", "button,input[type=button],input[type=submit],input[type=image],input[type=reset]")) {
			if (prop.val === "true") {
				prop.out = "pressed";
			} else {
				prop.out = "not pressed";
			}
		}
		pushProp();
	}
	if (hasProp("aria-roledescription")) {
		pushProp();
	}
	if (hasProp("aria-selected")) {
		if (hasRole("gridcell,option,row,tab,columnheader,rowheader,treeitem")) {
			if (prop.val === "true") {
				prop.out = "selected";
			} else {
				prop.out = "";
			}
		}	
		pushProp();
	}
	if (hasProp("contenteditable")) {
		if (prop.val === "") { //set to true
			prop.val = "true";
		}
		pushProp();
	}

	//===Get properties filtered by role/tag name

	if ($(element).is("input")) {
		//checked
		if (hasRole("", "input[type=checkbox],input[type=radio]")) {
			prop = { name: "", val: "" };
			if (element.checked)
				prop.out = "checked";
			else
				prop.out = "not checked";
			pushProp();
		}
	}

	//expanded/collapsed
	var expandedInOutput = false;
	if (!browserSupports.isIE && $(element).is("summary")) {
		if ($(element).closest("details").attr("open"))
			prop = { name: "open", val: "open", out: "expanded" };
		else
			prop = { name: "", val: "", out: "collapsed" };
		pushProp();
	}
	if (hasProp("aria-expanded")) {
		if (!expandedInOutput && hasRole("button,combobox,document,link,section,sectionhead,window", "button,a,section")) {
			if (prop.val === "true") {
				prop.out = "expanded";
			} else {
				prop.out = "collapsed";
			}
		}
		pushProp();
	}

	//heading level
	if (hasRole("heading", "h1,h2,h3,h4,h5,h6")) {
		var headingLevel = "2"; //default to 2 (defined in spec)
		if ($(element).is("[role=heading]")) {
			var ariaLevel = $(element).attr("aria-level");

			if (parseInt(ariaLevel) > 0 && parseInt(ariaLevel) == ariaLevel)
				headingLevel = ariaLevel;
		}
		else {//native heading tag
			headingLevel = $(element).prop("tagName").charAt(1);
		}
		prop = { name: "", val: "", out: "heading level " + headingLevel };
		pushProp();
	}

	//multiple
	if ($(element).is("select,input[type=file]")) {
		if (hasProp("multiple")) {
			prop.out = "multi-selectable";
			pushProp();
		}
	}

	//readonly
	var readonlyInOutput = false;
	if ($(element).is("input:not([type=radio],[type=checkbox]),textarea")) {
		if (hasProp("readonly")) {
			readonlyInOutput = true;
			prop.out = "readonly";
			pushProp();
		}
	}
	if (hasProp("aria-readonly")) {
		if (!readonlyInOutput && prop.val === "true" && hasRole("checkbox,combobox,grid,gridcell,listbox,radio,radiogroup,slider,spinbutton,textbox,columnheader,menuitemcheckbox,menuitemradio,rowheader,searchbox,switch,treegrid", "input:not([type=submit],[type=button],[type=image],[type=reset]),select,textarea")) {
			readonlyInOutput = true;
			prop.out = "readonly";
		}
		pushProp();
	}

	//required
	var requiredInOutput = false;
	if ($(element).is("input:not([type=submit],[type=button],[type=image],[type=reset]),textarea,select")) {
		if (hasProp("required")) {
			if (!readonlyInOutput) {//don't put required in output, if readonly is already there
				requiredInOutput = true;
				prop.out = "required";
			}
			pushProp();
		}
	}
	if (hasProp("aria-required")) {
		if (!readonlyInOutput && hasRole("checkbox,combobox,gridcell,listbox,radio,radiogroup,slider,spinbutton,textbox", "input:not([type=submit],[type=button],[type=image],[type=reset]),select,textarea")) {
			if (!requiredInOutput && prop.val === "true") {
				prop.out = "required";
			} else {
				prop.out = "";
			}
		}
			
		pushProp();
	}

	//radio button index
	if (hasRole("radio,menuitemradio", "input[type=radio]")) {
		prop = { name: "", val: "" };
		var group, radioIndex, radioCount = 0;
		if (elementData.role === "radio") {
			group = $(element).closest("[role=radiogroup]").find("[role=radio]");
		}
		else if (elementData.role === "menuitemradio") {
			group = $(element).closest("[role=group],[role=menu],[role=menubar]").find("[role=menuitemradio]");
		}
		else {//input[type=radio]
			var name = $(element).attr("name");
			if (name) { //get all radio buttons with this name
				group = $("#ANDI508-testPage input[type=radio][name]").filter(function () { return $(this).attr("name") === name; });
			}
			else //no name attribute. group of 1
				group = $(element);
		}
		if (group) {
			$(group).filter(":shown").each(function () {
				radioCount++;
				if ($(this).is(element)) //check if the radio button is this one
					radioIndex = radioCount; //set the index
			});
			prop.out = radioIndex + " of " + radioCount;
		}
		pushProp();
	}

	//sort
	if (hasRole("columnheader,rowheader", "th")) {
		if (hasProp("aria-sort")) {
			if (prop.val === "ascending") {
				prop.out = "ascending";
			} else {
				if (prop.val === "descending") {
					prop.out = "descending";
				} else {
					if (prop.val === "other") {
						prop.out = "other";
					} else {
						prop.out = "";
					}
				}
			}
			pushProp();
		}
	}
	else if (hasRole("link", "a")) {
		var header = $(element).parent();//using .parent() instead of .closest() to help with performance
		if ($(header).is("th,[role=columnheader],[role=rowheader]")) {
			var ariaSort = $(header).attr("aria-sort");
			var propOut = ""
			if (ariaSort) {
				if (ariaSort === "ascending") {
					propOut = "ascending";
				} else {
					if (ariaSort === "descending") {
						propOut = "descending";
					} else {
						if (ariaSort === "other") {
							propOut = "other";
						} else {
							propOut = "";
						}
					}
				}
				prop = {
					name: "aria-sort",
					val: ariaSort,
					out:  propOut
				};
				pushProp();
			}
		}
	}

	if (hasRole("range,scrollbar,separator,slider,spinbutton")) {
		if (hasProp("aria-valuemax"))
			pushProp();
		if (hasProp("aria-valuemin"))
			pushProp();

		var valuetextInOutput = false;
		if (hasRole("range,separator,slider")) {
			if (hasProp("aria-valuetext")) {
				valuetextInOutput = true;
				prop.out = prop.val;
				pushProp();
			}
		}
		if (hasProp("aria-valuenow")) {
			if (!valuetextInOutput) //valuetext overrides valuenow
				prop.out = prop.val;
			pushProp();
		}
	}

	//===Get properties already in AndiData
	if (elementData.accesskey) {
		var propVal = "";
		if (elementData.accesskey !== " ") {
			propVal = $.trim(elementData.accesskey.toUpperCase());
		} else {
			propVal = " ";
		}
		prop = {
			name: "accesskey",
			val:  propVal,
			out: "accesskey \"" + elementData.accesskey + "\""
		};
		pushProp();
	}
	if (elementData.tabindex) {
		prop = { name: "tabindex", val: elementData.tabindex };
		pushProp();
	}

	//===Get properties added by the module
	if (extraProps) {
		for (var p = 0; p < extraProps.length; p++) {
			if (extraProps[p]) {
				if (typeof extraProps[p] == "string")
					prop = { name: extraProps[p], val: $(element).attr(extraProps[p]) };
				else //typeof array (val needed extra logic that was done in module)
					prop = { name: extraProps[p][0], val: extraProps[p][1] };

				if (prop.val)
					pushProp();
			}
		}
	}

	//This function determines if the element has a role or tagname
	function hasRole(roles, tagNames) {
		if (roles.length > 0)
			roles = "[role=" + roles.replace(/,+/g, "],[role=") + "]";
		return $(element).isSemantically(roles, tagNames);
	}
	//This function determines if the element has an attribute
	function hasProp(attribute) {
		prop = {
			name: attribute,
			val: $(element).attr(attribute)
		};
		if (prop.val !== undefined)
			return true;
		return false;
	}
	//This function concatenates the output to addOnProps[0] and adds the property to the array
	function pushProp() {
		if (prop.out)
			addOnProps[0] += prop.out + ", ";
		addOnProps.push(prop);
	}

	function displayAsId(prop) {
		prop.val = "<span class='ANDI508-display-id'>#" + prop.val.replace(andiUtility.whitespace_regex, " #") + "</span>";
	}

	if (addOnProps[0] !== "")//Slice off last two characters: the comma and space: ", "
		addOnProps[0] = addOnProps[0].slice(0, -2);

	return addOnProps; //returns an array
};